apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-steps-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    workflows.argoproj.io/description: |
      This is a simple hello world example.
spec:
  entrypoint: template-a
  arguments:
    parameters:
      - name: message
        value: hello world
  templates:
  - name: template-a
    steps:
    - - name: a1
        template: template-b
        arguments:
          parameters:
            - name: message
              value: "Hello A1"
    - - name: a2
        template: template-b
        arguments:
          parameters:
            - name: message
              value: "Hello A2"
      - name: a3
        template: template-b
        arguments:
          parameters:
            - name: message
              value: "Hello A3"
  - name: template-b
    inputs:
      parameters:
        - name: message
    container:
      image: docker/whalesay:latest
      command: [ cowsay ]
      args: [ "{{inputs.parameters.message}}" ]
