apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    workflows.argoproj.io/description: |
      This is a simple hello world example.
spec:
  entrypoint: argo-dag
  arguments:
    parameters:
      - name: message
        value: Wellcome to Argo Workflow with DAG
  templates:
    - name: argo-dag-echo
      inputs:
        parameters:
          - name: message
      container:
        image: alpine:latest
        command: [ echo, "{{inputs.parameters.message}}" ]
    - name: argo-dag
      dag:
        tasks:
          - name: argo-dag-1
            template: argo-dag-echo
            arguments:
              parameters:
                - name: message
                  value: "Hello Argo DAG 1"
          - name: argo-dag-2
            template: argo-dag-echo
            arguments:
              parameters:
                - name: message
                  value: "Hello Argo DAG 2"
          - name: argo-dag-3
            template: argo-dag-echo
            depends: "argo-dag-1"
            arguments:
              parameters:
                - name: message
                  value: "Hello Argo DAG 3"
          - name: argo-dag-4
            template: argo-dag-echo
            depends: "argo-dag-2 && argo-dag-2"
            arguments:
              parameters:
                - name: message
                  value: "Hello Argo DAG 4"