apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    workflows.argoproj.io/description: |
      This is a simple hello world example.
spec:
  entrypoint: whalesay_with_parameter
  arguments:
    parameters:
      - name: message
        value: hello world
  templates:
    - name: whalesay_with_parameter
      inputs:
        parameters:
          - name: message
      container:
        image: docker/whalesay:latest
        command: [ cowsay ]
        args: [ "{{inputs.parameters.message}}" ]